parties: # parties default id
  guest:
    - 9999
  host:
    - 10000
    - 9999
  arbiter:
    - 10000

work_mode: 1 # 0 for standalone, or 1 for cluster

data_base_dir: "/Users/zhengquan/Code/SEED2022/seed2022" # path to project base where data is located